### ISSUE TITLE
question about usage WingetPathUpdater usage with gsudo

### ISSUE THREAD

**Issue by soredake** [jazzdelightsme/WingetPathUpdater#4]
For example, i will do `sudo { winget install Python.Python.3 }` with https://github.com/gerardog/gsudo to avoid uac (I have cache enabled), python will be installed, but the problem is, path will be reloaded in sudo { } scope, so I will still need to restart terminal in order to use python, is it possible to update env outside of sudo scope?

**Comment by jazzdelightsme** [comment]
That's a good question.

The same principles described in the main ReadMe would apply here:
 * Somehow, there will have to be code that runs in your shell.
 * There will need to be a "diff" (capture environment variables before, capture environment variables after, then compare).

You could do it manually, using the code in [WingetHelper.ps1](https://github.com/jazzdelightsme/WingetPathUpdater/blob/main/WingetHelper.ps1). Take a look at the code in [Winget.ps1](https://github.com/jazzdelightsme/WingetPathUpdater/blob/main/Winget.ps1) for how it is used.

If you wanted to make `sudo` magically do it for you, you would have to play the same trick on `sudo` that I played on `winget`: replace it with a shell script--so if you use PowerShell as your shell, you would have `sudo.ps1`, which would behave similarly to [Winget.ps1](https://github.com/jazzdelightsme/WingetPathUpdater/blob/main/Winget.ps1): capture current vars, "do the thing" (forward to the real `sudo`), capture vars again, compute and apply diff.

Out of curiosity, where do you get `sudo` from? I am familiar with the concept of "sudo", but I don't think I have ever used it on Windows.

**Comment by soredake** [comment]
> Out of curiosity, where do you get `sudo` from?

https://github.com/gerardog/gsudo, very convenient software.

**Comment by jazzdelightsme** [comment]
I see that gsudo already has a PowerShell module... it should be trivial for someone to port the functionality of this project to that one. (Wouldn't help if you use gsudo from one of the other shells it supports, but it probably wouldn't be too bad to handle those, too, the same way that [Winget.cmd](https://github.com/jazzdelightsme/WingetPathUpdater/blob/main/Winget.cmd) does it.)
